nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://www.beheall.com']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://www.beheall.com']
            allow_methods: ['POST']
            allow_headers: ['Content-Type']
            max_age: 3600